[platformio]
default_envs = osd_menu ; no_osd ; 
src_dir = RGB_TO_VGA_HDMI

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
platform_packages = framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git#5.5.1
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags =                           
  -O3
  -D PICO_STDIO_USB
build_unflags = 
  -Os
  -D PICO_STDIO_UART
build_src_filter =
  +<**/*.ino>
  +<**/*.cpp>
  +<**/*.c> 

[env:no_osd]
build_src_filter =
  ${env.build_src_filter}
  -<**/osd.c>
  -<**/osd_menu.c>

[env:osd_menu]
build_flags =
  ${env.build_flags}
  -D OSD_ENABLE
  -D OSD_MENU_ENABLE
build_src_filter =
  ${env.build_src_filter}
