[platformio]
default_envs = osd, ff-osd, osd-menu, no-osd

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
platform_packages = framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git#5.6.0
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags =
  -O3
  -D BOARD_36LJU22 ; BOARD_09LJV23 ; BOARD_25LEO25 ; BOARD_11XGA24 ; BOARD_38LJE24 ; 
  ; USB Host mode (USB keyboard): enable USB_KBD_ENABLE + NO_USB, disable PICO_STDIO_USB
  ; USB Device mode (Serial): enable PICO_STDIO_USB, disable USB_KBD_ENABLE + NO_USB
  -D USB_KBD_ENABLE
  -D NO_USB
  -D CFG_TUSB_CONFIG_FILE=\"tusb_config_host.h\"
  -I src
  -I src/video
  -I src/osd
  -I src/kbd
  -I src/usb
  -I src/i2c
  -I $PROJECT_PACKAGES_DIR/framework-arduinopico/pico-sdk/lib/tinyusb/src
build_unflags =
  -Os
  -D PICO_STDIO_UART
  -D PICO_STDIO_USB

[env:no-osd]
build_src_filter = +<*> -<osd/> -<kbd/> -<usb/> -<i2c/>

[env:osd-menu]
build_flags =
  ${env.build_flags}
  -D OSD_MENU_ENABLE
build_src_filter = +<*> -<osd/ff_osd.c> -<i2c/>

[env:ff-osd]
lib_archive = no
build_flags =
  ${env.build_flags}
  -D OSD_FF_ENABLE
build_src_filter = +<*> -<osd/osd_menu.c>

[env:osd]
lib_archive = no
build_flags =
  ${env.build_flags}
  -D OSD_MENU_ENABLE
  -D OSD_FF_ENABLE
