[platformio]
default_envs = osd ; ff_osd ; osd_menu ; no_osd ;    
src_dir = ZX_RGBI_TO_VGA_HDMI

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
platform_packages = framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git#5.5.1
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags =
  -O3
  -D PICO_STDIO_USB
  -D BOARD_36LJU22 ; BOARD_11XGA24 ; BOARD_LEO_REV3 ; BOARD_09LJV23 ; 
build_unflags =
  -Os
  -D PICO_STDIO_UART

[env:no_osd]

[env:osd_menu]
build_flags =
  ${env.build_flags}
  -D OSD_MENU_ENABLE

[env:ff_osd]
lib_archive = no
build_flags =
  ${env.build_flags}
  -D OSD_FF_ENABLE

[env:osd]
lib_archive = no
build_flags =
  ${env.build_flags}
  -D OSD_MENU_ENABLE
  -D OSD_FF_ENABLE
