// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// pio_ps2 //
// ------- //

#define pio_ps2_wrap_target 0
#define pio_ps2_wrap 4
#define pio_ps2_pio_version 0

#define pio_ps2_offset_wait_clk_low 1u
#define pio_ps2_offset_wait_clk_high 3u

static const uint16_t pio_ps2_program_instructions[] = {
            //     .wrap_target
    0xe02a, //  0: set    x, 10
    0x2000, //  1: wait   0 gpio, 0
    0x4001, //  2: in     pins, 1
    0x2080, //  3: wait   1 gpio, 0
    0x0041, //  4: jmp    x--, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_ps2_program = {
    .instructions = pio_ps2_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = pio_ps2_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config pio_ps2_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_ps2_wrap_target, offset + pio_ps2_wrap);
    return c;
}
#endif

// ---------- //
// pio_ch446q //
// ---------- //

#define pio_ch446q_wrap_target 0
#define pio_ch446q_wrap 5
#define pio_ch446q_pio_version 0

static const uint16_t pio_ch446q_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0xe026, //  1: set    x, 6            side 0
    0x6001, //  2: out    pins, 1         side 0
    0x0842, //  3: jmp    x--, 2          side 1
    0x6001, //  4: out    pins, 1         side 0
    0xb042, //  5: nop                    side 2
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_ch446q_program = {
    .instructions = pio_ch446q_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = pio_ch446q_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pio_ch446q_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_ch446q_wrap_target, offset + pio_ch446q_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

// ----------- //
// pio_epm3256 //
// ----------- //

#define pio_epm3256_wrap_target 0
#define pio_epm3256_wrap 7
#define pio_epm3256_pio_version 0

static const uint16_t pio_epm3256_program_instructions[] = {
            //     .wrap_target
    0x98a0, //  0: pull   block           side 3
    0xe03c, //  1: set    x, 28           side 0
    0x6001, //  2: out    pins, 1         side 0
    0x0842, //  3: jmp    x--, 2          side 1
    0x80a0, //  4: pull   block           side 0
    0xe03d, //  5: set    x, 29           side 0
    0x6001, //  6: out    pins, 1         side 0
    0x0846, //  7: jmp    x--, 6          side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_epm3256_program = {
    .instructions = pio_epm3256_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = pio_epm3256_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pio_epm3256_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_epm3256_wrap_target, offset + pio_epm3256_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

