// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// pio_ws2812 //
// ---------- //

#define pio_ws2812_wrap_target 0
#define pio_ws2812_wrap 8
#define pio_ws2812_pio_version 0

static const uint16_t pio_ws2812_program_instructions[] = {
            //     .wrap_target
    0xe039, //  0: set    x, 25           side 0
    0x0f41, //  1: jmp    x--, 1          side 0 [15]
    0x80a0, //  2: pull   block           side 0
    0xe057, //  3: set    y, 23           side 0
    0x6321, //  4: out    x, 1            side 0 [3]
    0x1228, //  5: jmp    !x, 8           side 1 [2]
    0x1284, //  6: jmp    y--, 4          side 1 [2]
    0x0200, //  7: jmp    0               side 0 [2]
    0x0284, //  8: jmp    y--, 4          side 0 [2]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_ws2812_program = {
    .instructions = pio_ws2812_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = pio_ws2812_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pio_ws2812_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_ws2812_wrap_target, offset + pio_ws2812_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

